apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-y48u
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-y48u
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-y48u
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-y48u
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-y48u
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qelz-tenant/rhtap-demo-app/hacbs-test-project-y48u@sha256:e0406ae3ef572a145148a03d3672ac8beba53091b14fd4f37fd4e37e8d8c5b06
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
