apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-y48u
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qelz-tenant/rhtap-demo-app/hacbs-test-project-y48u@sha256:e0406ae3ef572a145148a03d3672ac8beba53091b14fd4f37fd4e37e8d8c5b06
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
